#!/bin/sh /etc/rc.common

START=50

USE_PROCD=1
PROG=/usr/sbin/smtprelay

start_service() {
	procd_open_instance
	procd_set_param command "$PROG" -config /etc/smtprelay/smtprelay.ini
	procd_set_param respawn
	procd_close_instance
}
